### ISSUE TITLE
Too many columns for current window

### ISSUE THREAD

**Issue by frdmn** [IonicaBizau/ghcal#1]
Hello,

i'm using ZSH and iTerm2 and whenever i enter `ghcal frdmn`, the output doesn't fit into my terminal window:

![bildschirmfoto 2015-02-09 um 23 46 57](https://cloud.githubusercontent.com/assets/944459/6117633/2d9f267e-b0b6-11e4-95de-79bd06c982ed.png)

Even when i adjust the size and try again:

![bildschirmfoto 2015-02-09 um 23 49 29](https://cloud.githubusercontent.com/assets/944459/6117644/4d2fc516-b0b6-11e4-88fb-1e9c340999f6.png)

Any ideas?

**Comment by IonicaBizau** [comment]
You have to resize the window and rerun the command. I'm not sure what's the best solution for this problem...

**Comment by frdmn** [comment]
@IonicaBizau But then theres a new offset, no matter how I resize the window. (Except I make it huge so it "has to fit").

**Comment by IonicaBizau** [comment]
For me (and probably for you too), the width should be `118` columns. You can check that by `echo`ing the `$COLUMNS` variable:

``` sh
$ echo $COLUMNS
118
```

Can you confirm that?

**Comment by frdmn** [comment]
@IonicaBizau doesn't this depend on the columns of the last state of the window? 

When I turn off iTerm, reopen and open a new shell:

```
❯  ~  echo $COLUMNS
80
```

Ninja Edit: Same in OS X builtin Terminal.app

**Comment by IonicaBizau** [comment]
When you resize the terminal (increase the width), the `$COLUMNS` variable should increase too. So, increase the width to have a higher value than 118.

Maybe a good idea would be to display some points in the left side if the box doesn't fit correctly.

**Comment by frdmn** [comment]
Oh, is it a static width? I thought you try to calculate the current columns and adjust the output then.

**Comment by IonicaBizau** [comment]
Yes, it's a static width. It's not responsive. :smile:

Can you confirm that if you have a width higher than 118 it looks fine?

But we could make it responsive.

**Comment by frdmn** [comment]
@IonicaBizau Ah, my bad then. Yeah, it looks totally fine with 118 columns. I can even go down to 112 :)

**Comment by IonicaBizau** [comment]
Ah, nice! Probably if you write `ghcal ionicabizau` it will not look fine on 112 because my last two weeks from the calendar are hacked with commits in 2050. :smile:

**Comment by frdmn** [comment]
@IonicaBizau you're right! Thanks for your quick replies :+1:

**Comment by agauniyal** [comment]
I have 97 columns for medium sized and 197 for full-screen and it looks bad on both :/ . Responsive is the way to go.

**Comment by IonicaBizau** [comment]
@agauniyal Can you post a screenshot too?

**Comment by agauniyal** [comment]
@IonicaBizau  I hope these will do :smile:

![2015-02-28-224603_1366x768_scrot](https://cloud.githubusercontent.com/assets/7630575/6427086/d6c0d128-bf9b-11e4-975a-50ef3e961d9e.png)
![2015-02-28-224612_1366x768_scrot](https://cloud.githubusercontent.com/assets/7630575/6427089/d7a6e12c-bf9b-11e4-84dc-675dc392d1c3.png)
![2015-02-28-224617_1366x768_scrot](https://cloud.githubusercontent.com/assets/7630575/6427087/d79a464c-bf9b-11e4-8f28-cc113e2cefcd.png)
![2015-02-28-224633_1366x768_scrot](https://cloud.githubusercontent.com/assets/7630575/6427088/d7a272c2-bf9b-11e4-9fab-8ed86dfd8029.png)
![2015-02-28-224622_1366x768_scrot](https://cloud.githubusercontent.com/assets/7630575/6427085/d62e6bf8-bf9b-11e4-8e93-3e3689dec7bb.png)

**Comment by IonicaBizau** [comment]
@agauniyal Yeah, exactly. The first one proves that having enough columns solves the issue.

**Comment by IonicaBizau** [comment]
I'm going to close this here. Since `ghcal 2.0.0` uses `cli-gh-cal`, this is moved in https://github.com/IonicaBizau/cli-gh-cal/issues/2.

Contributions are welcome! :four_leaf_clover:

**Comment by IonicaBizau** [comment]
This should be fixed now via https://github.com/IonicaBizau/cli-gh-cal/pull/12.

`npm i -g ghcal@latest` should be enough. :tada:
