### ISSUE TITLE
How about bitbucket?

### ISSUE THREAD

**Issue by rollecode** [IonicaBizau/ghcal#25]
Is there any way to use Bitbucket with ghcal?

**Comment by IonicaBizau** [comment]
Does BitBucket provide such stats?

**Comment by rollecode** [comment]
I don't know, haven't investigated it further, just thought costs nothing to ask :) they have [something](https://blog.bitbucket.org/2015/08/05/awesome-graphs-for-bitbucket-visualized-statistics-for-git-and-mercurial-repositories/), I guess.

If you don't feel like implementing BitBucket, feel free to close this.
