### ISSUE TITLE
Squares do not appear properly.

### ISSUE THREAD

**Issue by SanketDG** [IonicaBizau/ghcal#5]
Hi.

I would love some help here, my terminal fails to display `ghcal` properly. I am pretty sure my terminal is `UTF-8`.

![image](https://cloud.githubusercontent.com/assets/8980971/8438848/0d8a093c-1f86-11e5-9973-f7ebf4ae4778.png)

**Comment by IonicaBizau** [comment]
Hey @SanketDG!

This is same like https://github.com/IonicaBizau/git-stats/issues/14. See [my comment](https://github.com/IonicaBizau/git-stats/issues/14#issuecomment-74870394) check if changing the font solves the issue.

Also, I'd be thankful if you found a square character like that, but which will be compatible with your current settings! :sparkles: 

Thanks!

**Comment by SanketDG** [comment]
I am not sure I understand what you mean, but take a look at `black small square` in this [page](http://unicodelookup.com/#square/1).

I'll try Menlo though.

**Comment by IonicaBizau** [comment]
@SanketDG Can you please post a screenshot with the following command and its output (but with your current settings, without changing anything, or if you changed something, rollback it)?

``` sh
echo "■ ▣ ◼ ◾ ▪"
```

We should find a compatible square. :four_leaf_clover:

**Comment by SanketDG** [comment]
Yes. this:

``` bash
■ ▣ ◼ ◾ ▪
```

**Comment by IonicaBizau** [comment]
@SanketDG And which one looks the best on your machine?

**Comment by SanketDG** [comment]
This is strange, right? Doesn't make sense. But when I change to a different font, this all stays the same except the graph appears like it should.

![image](https://cloud.githubusercontent.com/assets/8980971/8454904/5363c9d2-201e-11e5-9e4c-c4f3288ef9a8.png)

**Comment by IonicaBizau** [comment]
Cool! So, currently `■` is used in graph, but we should use `◼` (they are different, I checked it).

Could you please edit the square character in the git-stats-colors package?

``` js
open `npm config get prefix`/lib/node_modules/git-stats/node_modules/git-stats-colors/lib/index.js`
```

(maybe sudo is required)

And you should [look at this snippet](https://github.com/IonicaBizau/node-git-stats-colors/blob/8daf0dc7055419e4944f1693eb956641fa4cb567/lib/index.js#L11-L29): replace the black squares with `◼`. Save the file and run `git-stats`. Would like to see a screenshot. :smile:

**Comment by SanketDG** [comment]
Interesting, we are close!

![image](https://cloud.githubusercontent.com/assets/8980971/8456812/715ef1b6-202b-11e5-9a2a-16bc164c50ef.png)

Btw, this is `ghcal` repo, you are probably mistaken that this is `git-stats`.

**Comment by IonicaBizau** [comment]
True, true, true! But you've got it! You only need to replace the squares in the [right side](https://github.com/IonicaBizau/node-git-stats-colors/blob/8daf0dc7055419e4944f1693eb956641fa4cb567/lib/index.js#L16), so don't replace the key.

**Comment by SanketDG** [comment]
Oh, those were objects! Sorry for that. 

![image](https://cloud.githubusercontent.com/assets/8980971/8457447/fa125202-202e-11e5-81a6-f048c6cb2fb1.png)

**Comment by SanketDG** [comment]
By the way, I am trying to make something similar in a different language. Could I know, how you could print colors like that by just using ansi or something. Note that I do not have any of those libraries like `cheerio` or `couleurs`, so a "raw" way would be more helpful! Thanks!

**Comment by IonicaBizau** [comment]
> Could I know, how you could print colors like that by just using ansi or something. 

Yes, just use ANSI styles to style your strings. It's pretty easy to follow what happens in [`couleurs`](https://github.com/IonicaBizau/node-couleurs). Look at [these lines](https://github.com/IonicaBizau/node-couleurs/blob/07971e79000df007d02e1bcc4d9ef4a236c2a2c7/lib/index.js#L7-L15).

Like I always recommended, try and see what happens. For example do something like this:

``` sh
printf '\u001b[38;5;196mHello World!\u001b[0m'
```

This will show _Hello World_ in red foreground. BTW, what is the language you want to do something like this in?

PS: If you like to fix this bug in the `git-stats-colors` package, I'd be thankful! :smile:

**Comment by SanketDG** [comment]
> Yes, just use ANSI styles to style your strings. It's pretty easy to follow what happens in couleurs. Look at these lines.
> 
> Like I always recommended, try and see what happens. For example do something like this:
> 
> printf '\u001b[38;5;196mHello World!\u001b[0m'

Thanks for that. I think that will be a good start.

> BTW, what is the language you want to do something like this in?

Python! :)

> PS: If you like to fix this bug in the git-stats-colors package, I'd be thankful!

I again think you mean `ghcal`, but I could be wrong. I could send a pull request to both the repositories if you give the go!

**Comment by IonicaBizau** [comment]
> I again think you mean ghcal, but I could be wrong. I could send a pull request to both the repositories if you give the go!

@SanketDG Yep, actually, there are a three places where to fix this.
- [`git-stats`](https://github.com/IonicaBizau/git-stats/blob/5dd874245fc5b58d104e1ff1d04f203e1c383bd6/lib/index.js#L15)
- [`ghcal`](https://github.com/IonicaBizau/ghcal/blob/59899a18b40221577243254bc077a8a466246711/lib/index.js#L14)
- [`git-stats-colors`](https://github.com/IonicaBizau/node-git-stats-colors/blob/8daf0dc7055419e4944f1693eb956641fa4cb567/lib/index.js#L12-L27)

For colors in your app, you may check [this](https://pypi.python.org/pypi/ansicolors/1.0.2). Looks good. :smile:

**Comment by SanketDG** [comment]
> @SanketDG Yep, actually, there are a three places where to fix this.

Okay, I will send in pull requests to all of them!

> For colors in your app, you may check this. Looks good.

I have checked a couple of this, but bear with me here, how do you get those shades of green? that's what I'm scratching my head for.

**Comment by IonicaBizau** [comment]
@SanketDG Thanks! [`couleurs` accept rgb and hex inputs](https://github.com/IonicaBizau/node-couleurs/blob/07971e79000df007d02e1bcc4d9ef4a236c2a2c7/lib/index.js#L86-L92) and searches the nearest ANSI color via [`x256`](https://github.com/substack/node-x256) by @substack -- that's the secret.

**Comment by SanketDG** [comment]
@IonicaBizau okay, that should be good for a start, atleast now I can investigate on this. thanks!

**Comment by IonicaBizau** [comment]
:ship: 1.2.0 Thanks again!

Here are the @substack _public_ contributions on GitHub:

![image](https://cloud.githubusercontent.com/assets/2864371/8531151/0bb380dc-242e-11e5-931b-caf9dc8b39aa.png)
